// ─── Bruce Agent — Complete Mock Data ────────────────────────────────

export const mockUser = {
  id: "user-1",
  name: "Rafael Mendes",
  email: "rafael@email.com",
  phone: "+55 11 99999-0000",
  birthDate: "1990-04-15",
  avatar: null,
  plan: "plus" as "free" | "plus" | "pro",
  credits: {
    total: 10000,
    used: 3847,
    chatUsed: 2910,
    automationsUsed: 937,
    remaining: 6153,
  },
  joinedAt: "2025-10-01",
};

// ─── Chats / Histórico ──────────────────────────────────────────────
export const mockChats = [
  {
    id: "chat-1",
    title: "Planejamento da semana",
    preview: "Você tem 3 compromissos hoje: reunião às 10h, almoço com cliente às 12h30 e review do projeto às 16h.",
    date: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    pinned: true,
    integrations: ["google-calendar", "gmail"],
    messages: [
      {
        id: "m1",
        role: "user" as const,
        content: "O que tenho para fazer hoje e tem algum e-mail importante?",
        timestamp: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      },
      {
        id: "m2",
        role: "assistant" as const,
        content: "Você tem 3 compromissos hoje: reunião às 10h, almoço com cliente às 12h30 e review do projeto às 16h.\n\nNos e-mails, encontrei 2 importantes:\n• **Proposta da Acme Corp** — aguardando sua resposta até amanhã\n• **Fatura do plano Pro** — vencimento em 3 dias\n\nDeseja que eu tome alguma ação?",
        timestamp: new Date(Date.now() - 1000 * 60 * 9).toISOString(),
        toolCalls: [
          { tool: "google-calendar", label: "Consultando Google Calendar", result: "4 compromissos encontrados", expanded: false },
          { tool: "gmail", label: "Consultando Gmail", result: "3 e-mails relevantes encontrados", expanded: false },
        ],
        memoriesUsed: 2,
        rating: null,
      },
    ],
  },
  {
    id: "chat-2",
    title: "Resumo dos e-mails",
    preview: "Encontrei 7 e-mails não lidos. Os mais importantes são da Acme Corp e do banco.",
    date: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    pinned: false,
    integrations: ["gmail"],
    messages: [],
  },
  {
    id: "chat-3",
    title: "Criar evento no calendário",
    preview: "Evento 'Reunião com Design' criado para sexta-feira às 14h.",
    date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    pinned: false,
    integrations: ["google-calendar"],
    messages: [],
  },
  {
    id: "chat-4",
    title: "Análise financeira do mês",
    preview: "Seu saldo do mês está positivo em R$ 2.340. Há 2 faturas pendentes.",
    date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    pinned: false,
    integrations: [],
    messages: [],
  },
  {
    id: "chat-5",
    title: "Busca no Google Drive",
    preview: "Encontrei 3 arquivos relacionados ao projeto Alpha no seu Drive.",
    date: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    pinned: false,
    integrations: ["google-drive"],
    messages: [],
  },
  {
    id: "chat-6",
    title: "Notas da semana passada",
    preview: "Organizei suas anotações em 4 categorias: Trabalho, Pessoal, Ideias e Pendências.",
    date: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    pinned: false,
    integrations: [],
    messages: [],
  },
  {
    id: "chat-7",
    title: "Configurar automação diária",
    preview: "Automação criada: todo dia às 8h você receberá um resumo dos seus e-mails.",
    date: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    pinned: false,
    integrations: ["gmail"],
    messages: [],
  },
];

// ─── Integrações ─────────────────────────────────────────────────────
export const mockIntegrations = [
  {
    id: "gmail",
    name: "Gmail",
    description: "Leia, envie e gerencie seus e-mails diretamente pelo assistente.",
    category: "Comunicação",
    icon: "Mail",
    color: "#EA4335",
    connected: true,
    lastSync: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    permissions: ["Ler e-mails", "Enviar e-mails"],
    scopes: ["gmail.readonly", "gmail.send"],
    status: "connected" as const,
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Consulte e crie eventos na sua agenda automaticamente.",
    category: "Produtividade",
    icon: "Calendar",
    color: "#4285F4",
    connected: true,
    lastSync: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
    permissions: ["Visualizar eventos", "Criar eventos", "Editar eventos"],
    scopes: ["calendar.readonly", "calendar.events"],
    status: "connected" as const,
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Pesquise e acesse arquivos no seu Drive a qualquer momento.",
    category: "Armazenamento",
    icon: "HardDrive",
    color: "#0F9D58",
    connected: true,
    lastSync: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    permissions: ["Pesquisar arquivos", "Visualizar arquivos"],
    scopes: ["drive.readonly"],
    status: "connected" as const,
  },
  {
    id: "notion",
    name: "Notion",
    description: "Acesse páginas, bancos de dados e notas do Notion pelo chat.",
    category: "Produtividade",
    icon: "BookOpen",
    color: "#000000",
    connected: false,
    lastSync: null,
    permissions: ["Ler páginas", "Criar páginas", "Editar páginas"],
    scopes: ["read_content", "insert_content", "update_content"],
    status: "disconnected" as const,
  },
  {
    id: "github",
    name: "GitHub",
    description: "Consulte repositórios, issues e pull requests no chat.",
    category: "Dev",
    icon: "Github",
    color: "#24292e",
    connected: false,
    lastSync: null,
    permissions: ["Ler repositórios", "Ler issues"],
    scopes: ["repo:read", "issues:read"],
    status: "disconnected" as const,
  },
  {
    id: "slack",
    name: "Slack",
    description: "Leia e envie mensagens nos seus canais do Slack.",
    category: "Comunicação",
    icon: "MessageSquare",
    color: "#4A154B",
    connected: false,
    lastSync: null,
    permissions: ["Ler mensagens", "Enviar mensagens"],
    scopes: ["channels:read", "chat:write"],
    status: "disconnected" as const,
  },
  {
    id: "spotify",
    name: "Spotify",
    description: "Controle sua música e veja o que está tocando.",
    category: "Outros",
    icon: "Music",
    color: "#1DB954",
    connected: false,
    lastSync: null,
    permissions: ["Reprodução atual", "Controlar player"],
    scopes: ["user-read-playback-state", "user-modify-playback-state"],
    status: "disconnected" as const,
  },
  {
    id: "linear",
    name: "Linear",
    description: "Gerencie tarefas e projetos do Linear pelo assistente.",
    category: "Produtividade",
    icon: "CheckSquare",
    color: "#5E6AD2",
    connected: false,
    lastSync: null,
    permissions: ["Ler issues", "Criar issues"],
    scopes: ["issues:read", "issues:create"],
    status: "disconnected" as const,
  },
  {
    id: "dropbox",
    name: "Dropbox",
    description: "Acesse e gerencie arquivos no seu Dropbox.",
    category: "Armazenamento",
    icon: "Cloud",
    color: "#0061FF",
    connected: false,
    lastSync: null,
    permissions: ["Ler arquivos", "Listar pastas"],
    scopes: ["files.metadata.read", "files.content.read"],
    status: "disconnected" as const,
  },
  {
    id: "todoist",
    name: "Todoist",
    description: "Crie e consulte tarefas no Todoist pelo chat.",
    category: "Produtividade",
    icon: "ListTodo",
    color: "#DB4035",
    connected: false,
    lastSync: null,
    permissions: ["Ler tarefas", "Criar tarefas"],
    scopes: ["data:read", "task:add"],
    status: "disconnected" as const,
  },
  {
    id: "trello",
    name: "Trello",
    description: "Consulte cards e boards do Trello pelo assistente.",
    category: "Produtividade",
    icon: "Columns",
    color: "#0052CC",
    connected: false,
    lastSync: null,
    permissions: ["Ler boards", "Criar cards"],
    scopes: ["read", "write"],
    status: "disconnected" as const,
  },
  {
    id: "asana",
    name: "Asana",
    description: "Gerencie projetos e tarefas do Asana com IA.",
    category: "Produtividade",
    icon: "Target",
    color: "#F06A6A",
    connected: false,
    lastSync: null,
    permissions: ["Ler projetos", "Criar tarefas"],
    scopes: ["default"],
    status: "disconnected" as const,
  },
];

// ─── Financeiro ──────────────────────────────────────────────────────
export const financialCategories = [
  "Moradia", "Alimentação", "Transporte", "Saúde", "Educação",
  "Lazer", "Assinatura", "Salário", "Freelance", "Investimento",
  "Outros",
];

export const mockFinancialRecords = [
  {
    id: "fin-1", type: "fatura" as const,
    description: "Aluguel apartamento",
    amount: 2800, category: "Moradia",
    dueDate: "2026-09-25", paidDate: null,
    status: "pending" as const, recurring: true, receiptUrl: null,
  },
  {
    id: "fin-2", type: "fatura" as const,
    description: "Fatura Cartão Nubank",
    amount: 1450.90, category: "Outros",
    dueDate: "2026-09-28", paidDate: null,
    status: "pending" as const, recurring: true, receiptUrl: null,
  },
  {
    id: "fin-3", type: "fatura" as const,
    description: "Plano de saúde",
    amount: 380, category: "Saúde",
    dueDate: "2026-09-15", paidDate: "2026-09-14",
    status: "paid" as const, recurring: true, receiptUrl: null,
  },
  {
    id: "fin-4", type: "gasto" as const,
    description: "Supermercado Extra",
    amount: 312.50, category: "Alimentação",
    dueDate: "2026-09-18", paidDate: "2026-09-18",
    status: "paid" as const, recurring: false, receiptUrl: null,
  },
  {
    id: "fin-5", type: "gasto" as const,
    description: "Uber",
    amount: 87.20, category: "Transporte",
    dueDate: "2026-09-19", paidDate: "2026-09-19",
    status: "paid" as const, recurring: false, receiptUrl: null,
  },
  {
    id: "fin-6", type: "fatura" as const,
    description: "Netflix",
    amount: 55.90, category: "Assinatura",
    dueDate: "2026-09-10", paidDate: "2026-09-10",
    status: "paid" as const, recurring: true, receiptUrl: null,
  },
  {
    id: "fin-7", type: "fatura" as const,
    description: "Spotify",
    amount: 21.90, category: "Assinatura",
    dueDate: "2026-08-30", paidDate: null,
    status: "overdue" as const, recurring: true, receiptUrl: null,
  },
  {
    id: "fin-8", type: "recebimento" as const,
    description: "Salário — Empresa XYZ",
    amount: 8500, category: "Salário",
    dueDate: "2026-09-05", paidDate: "2026-09-05",
    status: "paid" as const, recurring: true, receiptUrl: null,
  },
  {
    id: "fin-9", type: "recebimento" as const,
    description: "Freelance — Projeto Alpha",
    amount: 3200, category: "Freelance",
    dueDate: "2026-09-12", paidDate: "2026-09-12",
    status: "paid" as const, recurring: false, receiptUrl: null,
  },
  {
    id: "fin-10", type: "recebimento" as const,
    description: "Dividendos — FIIs",
    amount: 420, category: "Investimento",
    dueDate: "2026-09-20", paidDate: null,
    status: "pending" as const, recurring: true, receiptUrl: null,
  },
];

// ─── Notas & Arquivos ─────────────────────────────────────────────────
export const mockNotes = [
  {
    id: "note-1", type: "note" as const,
    title: "Ideias para o produto",
    content: "# Ideias\n\n- Sistema de notificações proativas\n- Dashboard de insights semanais\n- Integração com Apple Calendar\n- Widget para iOS",
    tags: ["produto", "ideias"],
    favorite: true,
    createdAt: "2026-09-20T14:30:00Z",
    updatedAt: "2026-09-21T08:00:00Z",
  },
  {
    id: "note-2", type: "link" as const,
    title: "Documentação do Vercel AI SDK",
    content: "Referência completa da SDK de IA do Vercel",
    url: "https://sdk.vercel.ai/docs",
    tags: ["dev", "referência"],
    favorite: false,
    createdAt: "2026-09-19T10:00:00Z",
    updatedAt: "2026-09-19T10:00:00Z",
  },
  {
    id: "note-3", type: "pdf" as const,
    title: "Contrato de prestação de serviços",
    content: null,
    size: 2048000,
    tags: ["legal", "trabalho"],
    favorite: false,
    createdAt: "2026-09-15T09:00:00Z",
    updatedAt: "2026-09-15T09:00:00Z",
  },
  {
    id: "note-4", type: "image" as const,
    title: "Wireframe da home",
    content: null,
    size: 512000,
    tags: ["design", "produto"],
    favorite: true,
    createdAt: "2026-09-10T16:00:00Z",
    updatedAt: "2026-09-10T16:00:00Z",
  },
  {
    id: "note-5", type: "note" as const,
    title: "Rotina matinal",
    content: "1. Acordar 6h\n2. Meditação 10min\n3. Exercício 30min\n4. Leitura 20min\n5. Revisar agenda do dia",
    tags: ["pessoal", "rotina"],
    favorite: false,
    createdAt: "2026-09-08T07:00:00Z",
    updatedAt: "2026-09-18T07:00:00Z",
  },
  {
    id: "note-6", type: "audio" as const,
    title: "Gravação reunião cliente",
    content: null,
    size: 8192000,
    tags: ["trabalho", "reunião"],
    favorite: false,
    createdAt: "2026-09-05T15:00:00Z",
    updatedAt: "2026-09-05T15:00:00Z",
  },
  {
    id: "note-7", type: "link" as const,
    title: "Artigo sobre LLMs e memória",
    content: "Pesquisa sobre como modelos de linguagem implementam memória de longo prazo",
    url: "https://arxiv.org/abs/2304.11490",
    tags: ["ia", "pesquisa"],
    favorite: true,
    createdAt: "2026-09-01T11:00:00Z",
    updatedAt: "2026-09-01T11:00:00Z",
  },
  {
    id: "note-8", type: "pdf" as const,
    title: "Extrato bancário agosto",
    content: null,
    size: 156000,
    tags: ["financeiro"],
    favorite: false,
    createdAt: "2026-09-02T09:00:00Z",
    updatedAt: "2026-09-02T09:00:00Z",
  },
];

// ─── Memórias da IA ───────────────────────────────────────────────────
export const mockMemories = [
  {
    id: "mem-1",
    content: "Prefere respostas diretas e objetivas, sem rodeios.",
    type: "preferência" as const,
    source: "manual" as const,
    active: true,
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "mem-2",
    content: "Trabalha como desenvolvedor full-stack e empreendedor.",
    type: "pessoal" as const,
    source: "automático" as const,
    active: true,
    createdAt: "2026-09-03T14:00:00Z",
    updatedAt: "2026-09-15T08:00:00Z",
  },
  {
    id: "mem-3",
    content: "Mora em São Paulo, SP. Fuso horário: America/Sao_Paulo.",
    type: "pessoal" as const,
    source: "manual" as const,
    active: true,
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-01T10:00:00Z",
  },
  {
    id: "mem-4",
    content: "Prefere reuniões no período da tarde.",
    type: "preferência" as const,
    source: "automático" as const,
    active: true,
    createdAt: "2026-09-10T09:00:00Z",
    updatedAt: "2026-09-10T09:00:00Z",
  },
  {
    id: "mem-5",
    content: "Pratica exercícios físicos toda manhã antes das 7h.",
    type: "pessoal" as const,
    source: "automático" as const,
    active: false,
    createdAt: "2026-09-05T06:00:00Z",
    updatedAt: "2026-09-05T06:00:00Z",
  },
  {
    id: "mem-6",
    content: "Cliente principal: Empresa XYZ. Pagamento todo dia 5.",
    type: "trabalho" as const,
    source: "manual" as const,
    active: true,
    createdAt: "2026-09-08T11:00:00Z",
    updatedAt: "2026-09-08T11:00:00Z",
  },
  {
    id: "mem-7",
    content: "Não gosta de notificações fora do horário comercial (após 19h).",
    type: "preferência" as const,
    source: "manual" as const,
    active: true,
    createdAt: "2026-09-12T16:00:00Z",
    updatedAt: "2026-09-12T16:00:00Z",
  },
  {
    id: "mem-8",
    content: "Tem interesse em IA, startups e mercado de tecnologia.",
    type: "outros" as const,
    source: "automático" as const,
    active: true,
    createdAt: "2026-09-14T20:00:00Z",
    updatedAt: "2026-09-14T20:00:00Z",
  },
];

// ─── Automações ───────────────────────────────────────────────────────
export const mockAutomations = [
  {
    id: "auto-1",
    name: "Resumo matinal de e-mails",
    description: "Todo dia às 8h, resume os e-mails não lidos e cria uma nota.",
    trigger: "Diário às 08:00",
    triggerType: "schedule" as const,
    action: "Resumir e-mails → Criar nota",
    active: true,
    creditsPerRun: 45,
    runsThisMonth: 20,
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 6).toISOString(),
    integrations: ["gmail"],
    executions: [
      { id: "exec-1", date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), status: "success" as const, credits: 45, result: "7 e-mails resumidos, nota criada." },
      { id: "exec-2", date: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(), status: "success" as const, credits: 45, result: "3 e-mails resumidos, nota criada." },
      { id: "exec-3", date: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(), status: "error" as const, credits: 0, result: "Erro ao acessar o Gmail. Token expirado." },
    ],
  },
  {
    id: "auto-2",
    name: "Alerta de fatura próxima",
    description: "Quando uma fatura estiver a 3 dias do vencimento, avisa no chat.",
    trigger: "Verificação diária",
    triggerType: "event" as const,
    action: "Verificar faturas → Notificar no chat",
    active: true,
    creditsPerRun: 15,
    runsThisMonth: 6,
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    nextRun: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    integrations: [],
    executions: [
      { id: "exec-4", date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), status: "success" as const, credits: 15, result: "2 faturas identificadas com vencimento em 3 dias." },
    ],
  },
  {
    id: "auto-3",
    name: "Planejamento semanal",
    description: "Toda segunda às 7h, consulta compromissos e gera um plano para a semana.",
    trigger: "Segunda-feira às 07:00",
    triggerType: "schedule" as const,
    action: "Consultar agenda → Gerar planejamento → Criar nota",
    active: false,
    creditsPerRun: 80,
    runsThisMonth: 3,
    lastRun: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
    nextRun: null,
    integrations: ["google-calendar"],
    executions: [],
  },
];

// ─── Planos ───────────────────────────────────────────────────────────
export const plans = [
  {
    id: "free",
    name: "Free",
    price: 0,
    description: "Para experimentar o assistente.",
    credits: 500,
    features: [
      { label: "500 créditos/mês", included: true },
      { label: "Chat com IA (Bruce)", included: true },
      { label: "1 integração", included: true },
      { label: "10 memórias", included: true },
      { label: "100 MB de armazenamento", included: true },
      { label: "Histórico de 30 dias", included: true },
      { label: "Automações", included: false },
      { label: "Exportar dados", included: false },
      { label: "Suporte prioritário", included: false },
    ],
    model: "Bruce Base",
    memoryLimit: 10,
    storageGB: 0.1,
    automations: 0,
  },
  {
    id: "plus",
    name: "Plus",
    pricePerThousandCredits: 12.9,
    minCredits: 2000,
    maxCredits: 20000,
    description: "Para uso diário e produtividade real.",
    features: [
      { label: "Até 20.000 créditos/mês", included: true },
      { label: "Chat com IA (Bruce)", included: true },
      { label: "Integrações ilimitadas", included: true },
      { label: "100 memórias", included: true },
      { label: "5 GB de armazenamento", included: true },
      { label: "Histórico ilimitado", included: true },
      { label: "5 automações ativas", included: true },
      { label: "Exportar dados", included: true },
      { label: "Suporte prioritário", included: false },
    ],
    model: "Bruce Pro",
    memoryLimit: 100,
    storageGB: 5,
    automations: 5,
  },
  {
    id: "pro",
    name: "Pro",
    pricePerThousandCredits: 9.9,
    minCredits: 5000,
    maxCredits: 50000,
    description: "Para quem usa o assistente intensamente.",
    features: [
      { label: "Até 50.000 créditos/mês", included: true },
      { label: "Chat com IA (Bruce)", included: true },
      { label: "Integrações ilimitadas", included: true },
      { label: "Memórias ilimitadas", included: true },
      { label: "50 GB de armazenamento", included: true },
      { label: "Histórico ilimitado", included: true },
      { label: "Automações ilimitadas", included: true },
      { label: "Exportar dados", included: true },
      { label: "Suporte prioritário", included: true },
    ],
    model: "Bruce Pro Max",
    memoryLimit: -1,
    storageGB: 50,
    automations: -1,
  },
];

// ─── Histórico de pagamentos ─────────────────────────────────────────
export const mockPaymentHistory = [
  { id: "pay-1", date: "2026-09-05", description: "Plano Plus — 10.000 créditos", amount: 129, status: "paid" },
  { id: "pay-2", date: "2026-08-05", description: "Plano Plus — 10.000 créditos", amount: 129, status: "paid" },
  { id: "pay-3", date: "2026-07-05", description: "Plano Plus — 10.000 créditos", amount: 129, status: "paid" },
];

// ─── Suggestions (Chat empty state) ──────────────────────────────────
export const chatSuggestions = [
  { id: 1, text: "O que tenho hoje?", icon: "Calendar" },
  { id: 2, text: "Algum pagamento vencendo?", icon: "CreditCard" },
  { id: 3, text: "Resuma meus e-mails não lidos.", icon: "Mail" },
  { id: 4, text: "Quais são minhas prioridades?", icon: "Star" },
];
